import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter, Unbounded } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
const unbounded = Unbounded({ weight: '700', subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>yungrari</title>
        <meta name="description" content="Generated by Daniil Martynov ©" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Daniil Martynov, a.k.a <code className={styles.code}>yungrari</code>
            . Digital artist and musician based in 🇺🇦
          </p>
        </div>

        <div className={styles.center}>
          <a
            href="https://soundcloud.com/yungr4r1"
            target="_blank"
            rel="noopener noreferrer"
          >
            <span className={unbounded.className}>SOUNDCLOUD</span>

            <div className={styles.linkLogo}>
              <Image
                src="/soundcloud.svg"
                alt="SoundCloud"
                width={48}
                height={48}
                priority
              />
            </div>
          </a>
        </div>

        <div className={styles.grid}>
          <Link
            href="001.mp3"
            prefetch={false}
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              #WOD Type Beat 001 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>#INSTRUMENTAL #FREE</p>
          </Link>

          <Link
            href="002.mp3"
            prefetch={false}
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              #WOD Type Beat 002 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>#INSTRUMENTAL #FREE</p>
          </Link>

          <Link
            href="003.mp3"
            prefetch={false}
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              #WOD Type Beat 003 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>#INSTRUMENTAL #FREE</p>
          </Link>

          <Link
            href="004.mp3"
            prefetch={false}
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              #WOD Type Beat 004 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>#INSTRUMENTAL #FREE</p>
          </Link>
        </div>
      </main>
    </>
  )
}
